# Generated by Django 2.0.6 on 2018-07-13 14:25

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=17)),
                ('telephone', models.CharField(blank=True, max_length=17)),
                ('whatsapp', models.CharField(blank=True, max_length=17)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('address_line_1', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(max_length=50)),
                ('year_of_completion', models.IntegerField()),
                ('exam_type', models.CharField(max_length=20)),
                ('member_id', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=70)),
                ('reference_1', models.TextField(blank=True)),
                ('reference_2', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('executive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Alumni',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_paid', models.DateField(auto_now=True)),
                ('for_how_many_months', models.PositiveIntegerField(default=1)),
                ('year', models.PositiveIntegerField(default=2018)),
                ('alumnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='web.Alumnum')),
            ],
            options={
                'verbose_name_plural': 'Dues',
                'ordering': ('-date_paid',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('guests', models.CharField(blank=True, max_length=300)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=70)),
                ('position', models.CharField(max_length=70)),
                ('short_description', models.CharField(max_length=250)),
                ('job_description', models.TextField()),
                ('salary_range', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=70)),
                ('company', models.CharField(max_length=70)),
                ('how_to_apply', models.CharField(max_length=70)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('qualifications', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('profession_type', models.CharField(default='General', max_length=100)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='web.Alumnum')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_deadline', models.DateField()),
                ('least_contribution', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('project_images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, upload_to='images/'), size=None)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('school', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('how_to_apply', models.CharField(max_length=70)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='web.Alumnum')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='web.ProjectType'),
        ),
        migrations.AddField(
            model_name='alumnum',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='web.Chapter'),
        ),
        migrations.AddField(
            model_name='alumnum',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='web.House'),
        ),
        migrations.AddField(
            model_name='alumnum',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumnum', to=settings.AUTH_USER_MODEL),
        ),
    ]
