# Generated by Django 2.0.6 on 2018-06-19 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=17)),
                ('telephone', models.CharField(blank=True, max_length=17)),
                ('whatsapp', models.CharField(blank=True, max_length=17)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('address_line_1', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(max_length=50)),
                ('year_of_completion', models.IntegerField()),
                ('exam_type', models.CharField(max_length=20)),
                ('member_id', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_paid', models.DateField(auto_now=True)),
                ('alumnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='web.Alumnum')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=17)),
                ('year_of_completion', models.IntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.House')),
            ],
        ),
        migrations.AddField(
            model_name='alumnum',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='web.Chapter'),
        ),
        migrations.AddField(
            model_name='alumnum',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='web.House'),
        ),
        migrations.AddField(
            model_name='alumnum',
            name='reference_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnus_1', to='web.Reference'),
        ),
        migrations.AddField(
            model_name='alumnum',
            name='reference_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Reference'),
        ),
        migrations.AddField(
            model_name='alumnum',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumnum', to=settings.AUTH_USER_MODEL),
        ),
    ]
