# Generated by Django 2.0.6 on 2018-06-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='house',
        ),
        migrations.AlterField(
            model_name='alumnum',
            name='reference_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alumnum',
            name='reference_2',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
