# Generated by Django 2.0.6 on 2018-06-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180620_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=70)),
                ('position', models.CharField(max_length=70)),
                ('short_description', models.CharField(max_length=250)),
                ('job_description', models.TextField()),
                ('salary_range', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=70)),
                ('company', models.CharField(max_length=70)),
                ('how_to_apply', models.CharField(max_length=70)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('qualifications', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='alumnum',
            name='reference_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alumnum',
            name='reference_2',
            field=models.TextField(blank=True),
        ),
    ]
