# Generated by Django 2.0.6 on 2018-07-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180713_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='degree',
            field=models.CharField(default='All', max_length=50),
            preserve_default=False,
        ),
    ]
