# Generated by Django 2.0.6 on 2018-06-22 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180622_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2018, 6, 22, 10, 4, 28, 394261, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
