# Generated by Django 2.0.6 on 2018-07-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_scholarship_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='how_to_apply',
            field=models.CharField(max_length=300),
        ),
    ]
