# Generated by Django 2.0.6 on 2018-07-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180713_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='how_to_apply',
            field=models.TextField(),
        ),
    ]
