# Generated by Django 2.0.6 on 2018-06-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_job_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('school', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='alumnum',
            name='nickname',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='web.Alumnum'),
        ),
    ]
