# Generated by Django 2.0.6 on 2018-07-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_scholarship_how_to_apply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnum',
            options={'verbose_name_plural': 'Alumni'},
        ),
        migrations.AlterModelOptions(
            name='dues',
            options={'verbose_name_plural': 'Dues'},
        ),
        migrations.AddField(
            model_name='dues',
            name='for_how_many_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dues',
            name='year',
            field=models.PositiveIntegerField(default=2018),
        ),
    ]
