# Generated by Django 2.0.6 on 2018-07-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180703_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_deadline', models.DateField()),
                ('least_contribution', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.AlterModelOptions(
            name='dues',
            options={'ordering': ('-date_paid',), 'verbose_name_plural': 'Dues'},
        ),
    ]
