# Generated by Django 2.0.6 on 2018-07-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='short_description',
            field=models.TextField(),
        ),
    ]
