# Generated by Django 2.0.6 on 2018-07-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20180706_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('guests', models.CharField(max_length=300)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
    ]
