# Generated by Django 2.0.6 on 2018-07-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
